[tool.poetry]
name = "store sales"
version = "0.1.0"
description = ""
authors = ["middlepenguin <middlepenguin@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
ipykernel = "^6.25.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
